### Aula 01 - Delimitadores diferentes

In [1]:
# Rodar o código apenas uma vez para instalar a biblioteca pandas
# Depois comentar para evitar tentativas desnecessários
# !pip install pandas

# Importação do pandas para manipulação de dados
import pandas as pd

In [ ]:
# Carregando dataframe
# Errado - O delimitador padrão é ",", mas no dataset é "|"
df_errada = pd.read_csv('aula_01_dataset_1.csv') 
display(df_errada)

# Correto - Especificando o delimitador correto
df_correta = pd.read_csv('aula_01_dataset_1.csv', delimiter='|')
display(df_correta)

In [41]:
# Exemplo de dataset com delimitador errado e certo ao mesmo tempo
# Algumas colunas estão separadas por ";" e outras por "|"
df = pd.read_csv('aula_01_dataset_2.csv', delimiter='|')

# Vai printar o datraframe, mas perceba que as duas primeiras colunas aparece com o display, mas não fazem parte do 'df'. 
display(df)

# Para provar isso, basta chamar o método info() do dataframe
display(df.info())

# A forma mais correta de resolver isso é abrir o arquivo CSV em um editor de texto e corrigir o delimitador para que todas as colunas estejam separadas pelo mesmo caractere.
# Se quiser proceeeder, basta usar o método reset_index() do dataframe, passando o parâmetro inplace=True para modificar o dataframe original e drop=True para descartar a coluna de índice antiga.

df.reset_index(inplace=True, drop=True)
display(df)

,,ID_Produto;Nome_Produto,Categoria;Preco_Unitario,Estoque
101,Teclado Mecânico,Periféricos,250.0,15
102,Mouse Gamer,Periféricos,180.0,22
103,Monitor 24pol,Hardware,1200.0,8
104,Webcam HD,Acessórios,350.0,12
105,Headset Wireless,Áudio,450.0,10
106,SSD 1TB,Hardware,500.0,25
107,Cabo HDMI,Acessórios,45.0,50
108,Gabinete ATX,Hardware,400.0,5
109,Memória RAM 16GB,Hardware,380.0,18
110,Microfone USB,Áudio,600.0,7
111,Mousepad XL,Periféricos,120.0,30
112,Carregador Notebook,Acessórios,150.0,14
113,Placa de Vídeo,Hardware,2800.0,3
114,Cooler Fan,Hardware,80.0,40
115,Switch Ethernet,Redes,200.0,11
116,Roteador Wi-Fi 6,Redes,550.0,9
117,Suporte Monitor,Móveis,180.0,15
118,Teclado Membrana,Periféricos,90.0,20
119,Pendrive 64GB,Acessórios,60.0,100
120,Hub USB-C,Acessórios,130.0,25

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20 entries, (np.int64(101), 'Teclado Mecânico') to (np.int64(120), 'Hub USB-C')
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID_Produto;Nome_Produto   20 non-null     object
 1   Categoria;Preco_Unitario  20 non-null     float64
 2   Estoque                   20 non-null     int64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.9+ KB

None

   ID_Produto;Nome_Produto  Categoria;Preco_Unitario  Estoque
0              Periféricos                     250.0       15
1              Periféricos                     180.0       22
2                 Hardware                    1200.0        8
3               Acessórios                     350.0       12
4                    Áudio                     450.0       10
5                 Hardware                     500.0       25
6               Acessórios                      45.0       50
7                 Hardware                     400.0        5
8                 Hardware                     380.0       18
9                    Áudio                     600.0        7
10             Periféricos                     120.0       30
11              Acessórios                     150.0       14
12                Hardware                    2800.0        3
13                Hardware                      80.0       40
14                   Redes                     200.0       11
15                   Redes                     550.0        9
16                  Móveis                     180.0       15
17             Periféricos                      90.0       20
18              Acessórios                      60.0      100
19              Acessórios                     130.0       25