### Aula 03 - Espaços em branco

In [18]:
# Rodar o código apenas uma vez para instalar a biblioteca pandas
# Depois comentar para evitar tentar instalar novamente em execuções futuras
# !pip install pandas

# Importação do pandas para manipulação de dados
import pandas as pd

In [19]:
# Carregando dataframe
df = pd.read_csv('aula_03_dataset_1.csv')

# Inspeção visual do dataset
display(df)

# Cuidado!!! No display sai bonito, mas no df está com os espaços em branco
# Inspeção visual de um dos dados com espaços em branco
display("No dataframe tem os espaços em branco:")
display(df["Destino"][0])

# Removendo os espaços em branco
df["Destino"] = df["Destino"].str.strip()
display("Depois de removido os espaços em branco:")
display(df["Destino"][0])

   Cod_Carga        Destino Transportadora  Peso_KG        Status
0       C001            SP    TransRapido       450     Entregue
1       C002           Rio         JatoLog      120   Em Transito
2       C003             BH   TransRapido       300      Entregue
3       C004       Curitiba     LogBrasil       500     Pendente
4       C005             SP       JatoLog       210      Entregue
5       C006  Porto Alegre     TransRapido      180  Em Transito
6       C007            DF       LogBrasil      600      Entregue
7       C008        Manaus      TransNorte     1000      Pendente
8       C009         Recife    TransNorte       450     Entregue
9       C010            SP         JatoLog      320   Em Transito
10      C011      Salvador      LogBrasil       280      Entregue
11      C012      Fortaleza     TransNorte      550      Pendente
12      C013           Rio        JatoLog       150      Entregue
13      C014            BH     TransRapido      400   Em Transito
14      C015        Vitoria     LogBrasil       220     Entregue
15      C016             SP        JatoLog      190      Pendente
16      C017       Goiania     TransRapido      310      Entregue
17      C018         Cuiaba      LogBrasil      480   Em Transito
18      C019         Belém     TransNorte       700      Entregue
19      C020            SP        JatoLog       250      Pendente

'No dataframe tem os espaços em branco:'

' SP '

'Depois de removido os espaços em branco:'

'SP'

In [20]:
# Explo quando os espaços em branco estão no meio do texto
df = pd.read_csv('aula_03_dataset_2.csv')
display(df)
display(df["Destino"][0])
df["Destino"] = df["Destino"].str.strip()
display(df["Destino"][0])
df["Destino"] = df["Destino"].replace(r'\s+', ' ', regex=True)
display(df["Destino"][0])

  Cod_Carga                             Destino
0      C006  Porto       Alegre
1      C006                   São     Paulo

'Porto       Alegre                '

'Porto       Alegre'

'Porto Alegre'